export enum MyConstant {
  UNRECOGNIZED_USERNAME = 'UNRECOGNIZED_USERNAME',
  UNRECOGNIZED_USER_SESSION_ID = 'UNRECOGNIZED_USER_SESSION_ID',
  SERVICE_MESSAGE_CHAT_HAS_BEEN_CLOSED = 'SERVICE_MESSAGE_CHAT_HAS_BEEN_CLOSED',
  SORRY_CHAT_CLOSED = 'Sorry, your interlocutor has ended the chat.'
}
